pollapp/urls.py
from django.urls import path
from . import views

app_name = 'pollapp'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('question/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('question/<int:pk>/results/',
         views.ResultsView.as_view(), name='results'),
    path('question/<int:question_id>/vote/', views.vote, name='vote'),
]

polls/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pollapp.urls'))
]

pollapp/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    publish = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.publish >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

pollapp/views.py
from django.http.response import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.urls import reverse
from django.views import generic
from pollapp.models import Question, Choice

# Create your views here.


# def index(request):
#     latest_question_list = Question.objects.order_by('-publish')[:5]
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'pollapp/index.html', context)

class IndexView(generic.ListView):
    template_name = 'pollapp/index.html'
    context_object_name = 'latest_question_list'
    
    def get_queryset(self):
        return Question.objects.order_by('-publish')[:5]


# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'pollapp/detail.html', {'question': question})

class DetailView(generic.DetailView):
    model = Question
    template_name = 'pollapp/detail.html'


# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'pollapp/results.html', {'question': question})

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'pollapp/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'pollapp/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('pollapp:results', args=(question.id,)))

pollapp/templates/pollapp/detail.html
<form action="{% url 'pollapp:vote' question.id %}" method="post">
  {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        {% for choice in question.choice_set.all %}
            <input
            type="radio"
            name="choice"
            id="choice{{ forloop.counter }}"
            value="{{ choice.id }}"
            />
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label
            ><br />
        {% endfor %}
    </fieldset>
  <input type="submit" value="Vote" />
</form>

pollapp/templates/pollapp/index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li>
                <a href='{% url 'pollapp:detail' question.id %}'>{{ question.question_text }}</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls yet</p>
{% endif %}

pollapp/templates/pollapp/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'pollapp:detail' question.id %}">Vote again?</a>